package racingcar.constants

const val REQUEST_ENTER_CAR_NAME = "경주할 자동차 이름을 입력하세요.(이름은 쉼표(,) 기준으로 구분)"
const val QUESTION_NUMBER_OF_ATTEMPT = "시도할 횟수는 몇 회인가요?"
const val FINAL_WINNER = "최종 우승자 : "
const val EXECUTION_RESULT = "\n실행 결과"
const val ERROR_INPUT_CAR_NAMES_TWO_OR_MORE = "[Error] 자동차 이름은 2대 이상 입력해 주세요."
const val ERROR_SEPARATE_CAR_NAMES_COMMA = "[Error] 자동차 이름은 쉼표(,)로 구분해 주세요."
const val ERROR_NAME_DUPLICATION = "[Error] 중복된 이름은 작성할 수 없습니다."
const val ERROR_CAR_NAME_ONLY_FIVE_CHAR = "[Error] 자동차 이름은 5자 이하만 입력 가능합니다."
const val ERROR_CAR_NAME_CAN_NOT_BLANK = "[Error] 자동차 이름은 공란일 수 없습니다."
const val ERROR_INPUT_VALUE = "[Error] 값을 입력하세요."
const val ERROR_INPUT_NUMBER_ONLY = "[Error] 숫자만 입력하세요."
const val ERROR_INPUT_ONE_OR_MORE = "1 이상 입력 가능합니다."
const val BLANK = ""
const val SPACE = " "
const val ADVANCE = "-"
const val COMMA_AND_SPACE = ", "
const val COMMA = ","
